server:
  port: 9999

spring:
  application:
    name: snippetx-backend
  profiles:
    active: dev # 默认开发环境
  main:
    banner-mode: "off"

# MyBatis-Plus 核心配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.developer.snippetx.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 日志级别配置
logging:
  level:
    root: INFO
    com.developer.snippetx: DEBUG
